# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9df2ada5335663a1b8f1d251abad4fb8130c92a3a8b66d8528a8a42a9d9d1c7a9573dbe6c2d1ac4ed00d112fa8015e980496bb12c7736d59d1050561539be26

test:
  secret_key_base: f0a08faf0a301ff5a1a2d19cd38feeb87c73ea718069b8982f5e43495c3ff1ec70580570db30566739ac2a2261b365d6d792e4be2f609ee644b01fe15ad80138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
